#!/usr/bin/env bash
source Edit
source ./createDir.sh
DirArray=($BaseDir/GenomeRef $BaseDir/Annotation)
createDirIfMissing ${DirArray[@]}
cd $BaseDir/GenomeRef
wget $GenomeRefURL
gunzip $GenomeRef
cd $BaseDir/Annotation
wget $AnnoURL
gunzip $AnnoFName
